server:
  port: 10002

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka/
      #      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: plan-chat:10002 #重起名
    prefer-ip-address: true #访问路径可以显示IP地址
info:
  app.name: ximen-plan-chat
  company.name: www.ximen.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

user:
  password: ximen

jwt:
  config:
    key: ximen
    ttl: 360000
spring:
  application:
    name: plan-chat