server:
  port: 9999
eureka:
  instance:
    hostname: localhost # 注册中心服务的主机
  client:
    register-with-eureka: false # 是否当前微服务注册到EureKa服务中。自己是注册中心，因此无需注册
    fetch-registry: false # Eureka客户端与与Eureka服务端进行交互的地址Map表 alse表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:9999/eureka/
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。